name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true


jobs:
  sdist:
    name: Source distribution
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: "3.12"
      - name: Create sdist
        run: |
          python -m pip install --upgrade build
          python -m build --sdist
        shell: bash
      - name: List output directory
        run: ls -lh dist/bagz*.tar.gz
        shell: bash
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: bagz-sdist
          path: dist/bagz*.tar.gz
      - name: Upload Release Asset
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@a74c266d4acb74d5b14599995014b2356c7342a8
        with:
          files: dist/bagz*.tar.gz

  bdist-wheel:
    name: Build wheels on ${{ matrix.os }} for python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["310", "311", "312", "313"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: "3.12"
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.2.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp${{ matrix.python-version }}-manylinux_x86_64"
          CIBW_BUILD_VERBOSITY: 1
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: bagz-bdist-wheel-${{ matrix.os }}-${{ strategy.python-version }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl
      - name: Upload Release Asset
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@a74c266d4acb74d5b14599995014b2356c7342a8
        with:
          files: wheelhouse/*.whl
